"""Import every mapper so ``Base.metadata`` is complete."""

from app.db.base import Base
from app.db.models.core import (
    Account,
    Customer,
    DeadLetterEvent,
    Device,
    DeviceLink,
    IngestedEvent,
    Merchant,
    Transaction,
    TransactionFeature,
)
from app.db.models.identity import (
    AuditLog,
    Notification,
    Permission,
    Policy,
    RefreshToken,
    RoleRecord,
    User,
    role_permissions,
    user_roles,
)
from app.db.models.mlops import (
    DriftMetric,
    FeedbackLabel,
    ModelMetric,
    ModelVersion,
    TrainingRun,
)
from app.db.models.platform import (
    AIQuery,
    Dataset,
    DemoScenarioRun,
    LineageEdge,
    PipelineRun,
    QualityCheck,
    SystemMetric,
)
from app.db.models.risk import (
    Alert,
    Case,
    CaseEvent,
    CaseNote,
    Decision,
    FraudPrediction,
    FraudRing,
    FraudRingMember,
    RiskScore,
    Rule,
    RuleExecution,
)

__all__ = [
    "AIQuery",
    "Account",
    "Alert",
    "AuditLog",
    "Base",
    "Case",
    "CaseEvent",
    "CaseNote",
    "Customer",
    "Dataset",
    "DeadLetterEvent",
    "Decision",
    "DemoScenarioRun",
    "Device",
    "DeviceLink",
    "DriftMetric",
    "FeedbackLabel",
    "FraudPrediction",
    "FraudRing",
    "FraudRingMember",
    "IngestedEvent",
    "LineageEdge",
    "Merchant",
    "ModelMetric",
    "ModelVersion",
    "Notification",
    "Permission",
    "PipelineRun",
    "Policy",
    "QualityCheck",
    "RefreshToken",
    "RiskScore",
    "RoleRecord",
    "Rule",
    "RuleExecution",
    "SystemMetric",
    "TrainingRun",
    "Transaction",
    "TransactionFeature",
    "User",
    "role_permissions",
    "user_roles",
]
