"""initial schema

Revision ID: 3c4ae565a3f6
Revises: 
Create Date: 2026-08-24 18:27:57.367826
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c4ae565a3f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_queries',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_roles', sa.JSON(), nullable=False),
    sa.Column('surface', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=48), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('sql_valid', sa.Boolean(), nullable=True),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_queries'))
    )
    with op.batch_alter_table('ai_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_queries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_queries_intent'), ['intent'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_queries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_queries_surface'), ['surface'], unique=False)
        batch_op.create_index('ix_ai_queries_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_roles', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('rule_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_time', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_number', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=28), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=True),
    sa.Column('merchant_id', sa.String(length=40), nullable=True),
    sa.Column('primary_transaction_id', sa.String(length=48), nullable=True),
    sa.Column('fraud_ring_id', sa.String(length=40), nullable=True),
    sa.Column('exposure_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=40), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=160), nullable=True),
    sa.Column('opened_by', sa.String(length=64), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=40), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index('ix_cases_assignee_status', ['assigned_to', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_fraud_ring_id'), ['fraud_ring_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_resolution'), ['resolution'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_risk_band'), ['risk_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)
        batch_op.create_index('ix_cases_status_priority', ['status', 'priority'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('kyc_status', sa.String(length=24), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('home_latitude', sa.Float(), nullable=True),
    sa.Column('home_longitude', sa.Float(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenure_days', sa.Integer(), nullable=False),
    sa.Column('avg_transaction_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('std_transaction_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('max_transaction_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('lifetime_value', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('typical_merchant_category', sa.String(length=48), nullable=True),
    sa.Column('typical_hour', sa.Integer(), nullable=True),
    sa.Column('distinct_device_count', sa.Integer(), nullable=False),
    sa.Column('chargeback_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_fraud_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('risk_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watchlisted', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_country'), ['country'], unique=False)
        batch_op.create_index('ix_customers_country_segment', ['country', 'segment'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_customers_risk', ['risk_band', 'risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_risk_band'), ['risk_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_segment'), ['segment'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_watchlisted'), ['watchlisted'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('layer', sa.String(length=24), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('steward', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.String(length=24), nullable=False),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('refresh_cadence', sa.String(length=48), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_sla_minutes', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_layer'), ['layer'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_datasets_quality_score'), ['quality_score'], unique=False)

    op.create_table('dead_letter_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_events'))
    )
    with op.batch_alter_table('dead_letter_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letter_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letter_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letter_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dead_letter_events_topic'), ['topic'], unique=False)

    op.create_table('demo_scenario_runs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('scenario_key', sa.String(length=48), nullable=False),
    sa.Column('scenario_name', sa.String(length=120), nullable=False),
    sa.Column('triggered_by', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('transaction_ids', sa.JSON(), nullable=False),
    sa.Column('case_ids', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demo_scenario_runs'))
    )
    with op.batch_alter_table('demo_scenario_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demo_scenario_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_demo_scenario_runs_scenario_key'), ['scenario_key'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=24), nullable=False),
    sa.Column('os', sa.String(length=32), nullable=False),
    sa.Column('browser', sa.String(length=48), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('distinct_customers', sa.Integer(), nullable=False),
    sa.Column('distinct_ips', sa.Integer(), nullable=False),
    sa.Column('fraud_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_emulator', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_distinct_customers'), ['distinct_customers'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_is_blacklisted'), ['is_blacklisted'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_risk_score'), ['risk_score'], unique=False)

    op.create_table('drift_metrics',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('model_version_id', sa.String(length=48), nullable=True),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('drift_type', sa.String(length=24), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('psi', sa.Float(), nullable=False),
    sa.Column('ks_statistic', sa.Float(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('current_mean', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('baseline_window', sa.String(length=48), nullable=False),
    sa.Column('current_window', sa.String(length=48), nullable=False),
    sa.Column('bins', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drift_metrics'))
    )
    with op.batch_alter_table('drift_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_drift_feature_time', ['feature_name', 'computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_metrics_drift_type'), ['drift_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_metrics_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_metrics_status'), ['status'], unique=False)

    op.create_table('fraud_rings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('detection_method', sa.String(length=48), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('fraud_probability', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('shared_devices', sa.JSON(), nullable=False),
    sa.Column('shared_ips', sa.JSON(), nullable=False),
    sa.Column('shared_merchants', sa.JSON(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_rings'))
    )
    with op.batch_alter_table('fraud_rings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_rings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_rings_detection_method'), ['detection_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_rings_member_count'), ['member_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_rings_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_rings_status'), ['status'], unique=False)

    op.create_table('ingested_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_ingested_events'))
    )
    with op.batch_alter_table('ingested_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingested_events_processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingested_events_topic'), ['topic'], unique=False)

    op.create_table('lineage_edges',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('transformation', sa.String(length=160), nullable=False),
    sa.Column('processor', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineage_edges'))
    )
    with op.batch_alter_table('lineage_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineage_edges_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_lineage_source_target', ['source', 'target'], unique=True)

    op.create_table('merchants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('mcc', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('transaction_volume', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('fraud_count', sa.Integer(), nullable=False),
    sa.Column('fraud_rate', sa.Float(), nullable=False),
    sa.Column('chargeback_rate', sa.Float(), nullable=False),
    sa.Column('avg_ticket', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('risk_category', sa.String(length=24), nullable=False),
    sa.Column('high_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_category'), ['category'], unique=False)
        batch_op.create_index('ix_merchants_category_risk', ['category', 'risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_fraud_rate'), ['fraud_rate'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_high_risk_flag'), ['high_risk_flag'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_risk_band'), ['risk_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_risk_score'), ['risk_score'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=48), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('artifact_path', sa.String(length=400), nullable=True),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('validation_rows', sa.Integer(), nullable=False),
    sa.Column('test_rows', sa.Integer(), nullable=False),
    sa.Column('positive_rate', sa.Float(), nullable=False),
    sa.Column('training_seconds', sa.Float(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trained_by', sa.String(length=120), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by', sa.String(length=120), nullable=True),
    sa.Column('training_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('mlflow_model_uri', sa.String(length=400), nullable=True),
    sa.Column('baseline_stats', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions'))
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_name'), ['name'], unique=False)
        batch_op.create_index('ix_model_versions_name_stage', ['name', 'stage'], unique=False)
        batch_op.create_index('ix_model_versions_name_version', ['name', 'version'], unique=True)
        batch_op.create_index(batch_op.f('ix_model_versions_stage'), ['stage'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('target_role', sa.String(length=48), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_target_role'), ['target_role'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_created_at'), ['created_at'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('pipeline', sa.String(length=80), nullable=False),
    sa.Column('pipeline_type', sa.String(length=24), nullable=False),
    sa.Column('run_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('records_in', sa.Integer(), nullable=False),
    sa.Column('records_out', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=120), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_pipeline'), ['pipeline'], unique=False)
        batch_op.create_index('ix_pipeline_runs_pipeline_time', ['pipeline', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_run_key'), ['run_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_status'), ['status'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enforced', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('key', name='uq_policies_key')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_created_at'), ['created_at'], unique=False)

    op.create_table('quality_checks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('dataset', sa.String(length=120), nullable=False),
    sa.Column('check_name', sa.String(length=120), nullable=False),
    sa.Column('dimension', sa.String(length=24), nullable=False),
    sa.Column('expectation', sa.String(length=255), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rows_scanned', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_checks'))
    )
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_checks_dataset'), ['dataset'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_checks_status'), ['status'], unique=False)
        batch_op.create_index('ix_quality_dataset_time', ['dataset', 'run_at'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('rules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('risk_points', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('true_positive_count', sa.Integer(), nullable=False),
    sa.Column('false_positive_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index('ix_rules_active_priority', ['is_active', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_priority'), ['priority'], unique=False)

    op.create_table('system_metrics',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_metrics'))
    )
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metrics_component'), ['component'], unique=False)
        batch_op.create_index('ix_system_metrics_name_time', ['name', 'recorded_at'], unique=False)

    op.create_table('training_runs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('experiment', sa.String(length=80), nullable=False),
    sa.Column('run_name', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('dataset_rows', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=120), nullable=False),
    sa.Column('model_version_id', sa.String(length=48), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_runs'))
    )
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_experiment'), ['experiment'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_runs_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('account_type', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('masked_number', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_accounts_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_status'), ['status'], unique=False)

    op.create_table('case_events',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_events_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_events'))
    )
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.create_index('ix_case_events_case_time', ['case_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_events_event_type'), ['event_type'], unique=False)

    op.create_table('case_notes',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('author_id', sa.String(length=40), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_notes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_notes'))
    )
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_notes_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_notes_created_at'), ['created_at'], unique=False)

    op.create_table('device_links',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('fraud_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_device_links_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_links_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_links'))
    )
    with op.batch_alter_table('device_links', schema=None) as batch_op:
        batch_op.create_index('ix_device_links_customer', ['customer_id'], unique=False)
        batch_op.create_index('ix_device_links_device', ['device_id'], unique=False)

    op.create_table('fraud_ring_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ring_id', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('role_in_ring', sa.String(length=32), nullable=False),
    sa.Column('centrality', sa.Float(), nullable=False),
    sa.Column('risk_contribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ring_id'], ['fraud_rings.id'], name=op.f('fk_fraud_ring_members_ring_id_fraud_rings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_ring_members'))
    )
    with op.batch_alter_table('fraud_ring_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_ring_members_ring_id'), ['ring_id'], unique=False)
        batch_op.create_index('ix_ring_members_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('model_metrics',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('model_version_id', sa.String(length=48), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window', sa.String(length=24), nullable=False),
    sa.Column('metric_name', sa.String(length=48), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_warning', sa.Float(), nullable=True),
    sa.Column('threshold_critical', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_model_metrics_model_version_id_model_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metrics'))
    )
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_metrics_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index('ix_model_metrics_model_time', ['model_version_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metrics_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.Column('permission_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=True),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('merchant_category', sa.String(length=48), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('transaction_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('fraud_probability', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('graph_risk', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('processing_ms', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.Column('fraud_type', sa.String(length=48), nullable=True),
    sa.Column('label_source', sa.String(length=32), nullable=True),
    sa.Column('labelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_transactions_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_transactions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_transactions_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_transactions_customer_time', ['customer_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_decision'), ['decision'], unique=False)
        batch_op.create_index('ix_transactions_decision_time', ['decision', 'occurred_at'], unique=False)
        batch_op.create_index('ix_transactions_device_time', ['device_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_event_id'), ['event_id'], unique=True)
        batch_op.create_index('ix_transactions_fraud', ['is_fraud', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_fraud_type'), ['fraud_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_category'), ['merchant_category'], unique=False)
        batch_op.create_index('ix_transactions_merchant_time', ['merchant_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_payment_method'), ['payment_method'], unique=False)
        batch_op.create_index('ix_transactions_risk', ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_risk_band'), ['risk_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=True),
    sa.Column('customer_id', sa.String(length=40), nullable=True),
    sa.Column('merchant_id', sa.String(length=40), nullable=True),
    sa.Column('alert_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('triggered_rules', sa.JSON(), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_alerts_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index('ix_alerts_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=48), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('triggered_rules', sa.JSON(), nullable=False),
    sa.Column('processing_ms', sa.Float(), nullable=False),
    sa.Column('overridden_by', sa.String(length=64), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_decisions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decisions_outcome_time', ['outcome', 'decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('feedback_labels',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analyst_id', sa.String(length=40), nullable=True),
    sa.Column('analyst_name', sa.String(length=160), nullable=False),
    sa.Column('predicted_probability', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('used_in_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_feedback_labels_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_labels'))
    )
    with op.batch_alter_table('feedback_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_labels_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_labels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_labels_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_labels_verdict'), ['verdict'], unique=False)
        batch_op.create_index('ix_feedback_used_time', ['used_in_training', 'created_at'], unique=False)

    op.create_table('fraud_predictions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('probability', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('predicted_label', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('inference_ms', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_fraud_predictions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_predictions'))
    )
    with op.batch_alter_table('fraud_predictions', schema=None) as batch_op:
        batch_op.create_index('ix_fraud_predictions_model_time', ['model_version', 'predicted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_predictions_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_predictions_probability'), ['probability'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_predictions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('risk_scores',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('fraud_probability', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('customer_risk', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('merchant_risk', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('graph_risk', sa.Numeric(precision=9, scale=6, asdecimal=False), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('triggered_rules', sa.JSON(), nullable=False),
    sa.Column('top_factors', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('ruleset_version', sa.String(length=64), nullable=True),
    sa.Column('latency_breakdown', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_risk_scores_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_scores_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_final_score'), ['final_score'], unique=False)
        batch_op.create_index('ix_risk_scores_time_band', ['scored_at', 'risk_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('rule_executions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('rule_id', sa.String(length=40), nullable=False),
    sa.Column('rule_code', sa.String(length=48), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('risk_points', sa.Float(), nullable=False),
    sa.Column('evaluation_ms', sa.Float(), nullable=False),
    sa.Column('matched_values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_executions_rule_id_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_rule_executions_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_executions'))
    )
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.create_index('ix_rule_executions_rule_time', ['rule_id', 'evaluated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_executions_triggered'), ['triggered'], unique=False)
        batch_op.create_index('ix_rule_executions_txn', ['transaction_id'], unique=False)

    op.create_table('transaction_features',
    sa.Column('transaction_id', sa.String(length=48), nullable=False),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=24), nullable=False),
    sa.Column('computation_ms', sa.Float(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('amount_log', sa.Float(), nullable=False),
    sa.Column('amount_zscore', sa.Float(), nullable=False),
    sa.Column('amount_ratio_to_avg', sa.Float(), nullable=False),
    sa.Column('amount_percentile', sa.Float(), nullable=False),
    sa.Column('txn_count_1m', sa.Integer(), nullable=False),
    sa.Column('txn_count_5m', sa.Integer(), nullable=False),
    sa.Column('txn_count_1h', sa.Integer(), nullable=False),
    sa.Column('txn_count_24h', sa.Integer(), nullable=False),
    sa.Column('amount_sum_1h', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('amount_sum_24h', sa.Numeric(precision=18, scale=2, asdecimal=False), nullable=False),
    sa.Column('seconds_since_prev', sa.Float(), nullable=False),
    sa.Column('distance_from_prev_km', sa.Float(), nullable=False),
    sa.Column('velocity_kmh', sa.Float(), nullable=False),
    sa.Column('impossible_travel', sa.Integer(), nullable=False),
    sa.Column('country_change', sa.Integer(), nullable=False),
    sa.Column('is_new_device', sa.Integer(), nullable=False),
    sa.Column('device_customer_count', sa.Integer(), nullable=False),
    sa.Column('device_risk', sa.Float(), nullable=False),
    sa.Column('merchant_fraud_rate', sa.Float(), nullable=False),
    sa.Column('merchant_risk', sa.Float(), nullable=False),
    sa.Column('is_new_merchant_for_customer', sa.Integer(), nullable=False),
    sa.Column('category_mismatch', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_night', sa.Integer(), nullable=False),
    sa.Column('hour_deviation', sa.Float(), nullable=False),
    sa.Column('customer_tenure_days', sa.Integer(), nullable=False),
    sa.Column('customer_txn_count', sa.Integer(), nullable=False),
    sa.Column('customer_prior_fraud', sa.Integer(), nullable=False),
    sa.Column('ip_customer_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_features_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transaction_features'))
    )
    with op.batch_alter_table('transaction_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_features_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_features_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_features_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_features_computed_at'))

    op.drop_table('transaction_features')
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_rule_executions_txn')
        batch_op.drop_index(batch_op.f('ix_rule_executions_triggered'))
        batch_op.drop_index('ix_rule_executions_rule_time')

    op.drop_table('rule_executions')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_scores_transaction_id'))
        batch_op.drop_index('ix_risk_scores_time_band')
        batch_op.drop_index(batch_op.f('ix_risk_scores_final_score'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_customer_id'))

    op.drop_table('risk_scores')
    with op.batch_alter_table('fraud_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_predictions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_fraud_predictions_probability'))
        batch_op.drop_index(batch_op.f('ix_fraud_predictions_outcome'))
        batch_op.drop_index('ix_fraud_predictions_model_time')

    op.drop_table('fraud_predictions')
    with op.batch_alter_table('feedback_labels', schema=None) as batch_op:
        batch_op.drop_index('ix_feedback_used_time')
        batch_op.drop_index(batch_op.f('ix_feedback_labels_verdict'))
        batch_op.drop_index(batch_op.f('ix_feedback_labels_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_labels_created_at'))
        batch_op.drop_index(batch_op.f('ix_feedback_labels_case_id'))

    op.drop_table('feedback_labels')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_transaction_id'))
        batch_op.drop_index('ix_decisions_outcome_time')

    op.drop_table('decisions')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_transaction_id'))
        batch_op.drop_index('ix_alerts_status_severity')
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_risk_score'))
        batch_op.drop_index(batch_op.f('ix_alerts_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_case_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_session_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_risk_band'))
        batch_op.drop_index('ix_transactions_risk')
        batch_op.drop_index(batch_op.f('ix_transactions_payment_method'))
        batch_op.drop_index(batch_op.f('ix_transactions_occurred_at'))
        batch_op.drop_index('ix_transactions_merchant_time')
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_demo'))
        batch_op.drop_index(batch_op.f('ix_transactions_ip_address'))
        batch_op.drop_index(batch_op.f('ix_transactions_fraud_type'))
        batch_op.drop_index('ix_transactions_fraud')
        batch_op.drop_index(batch_op.f('ix_transactions_event_id'))
        batch_op.drop_index('ix_transactions_device_time')
        batch_op.drop_index('ix_transactions_decision_time')
        batch_op.drop_index(batch_op.f('ix_transactions_decision'))
        batch_op.drop_index('ix_transactions_customer_time')
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_country'))
        batch_op.drop_index(batch_op.f('ix_transactions_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_channel'))
        batch_op.drop_index(batch_op.f('ix_transactions_amount'))

    op.drop_table('transactions')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_metrics_status'))
        batch_op.drop_index('ix_model_metrics_model_time')
        batch_op.drop_index(batch_op.f('ix_model_metrics_metric_name'))

    op.drop_table('model_metrics')
    with op.batch_alter_table('fraud_ring_members', schema=None) as batch_op:
        batch_op.drop_index('ix_ring_members_entity')
        batch_op.drop_index(batch_op.f('ix_fraud_ring_members_ring_id'))

    op.drop_table('fraud_ring_members')
    with op.batch_alter_table('device_links', schema=None) as batch_op:
        batch_op.drop_index('ix_device_links_device')
        batch_op.drop_index('ix_device_links_customer')

    op.drop_table('device_links')
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_notes_created_at'))
        batch_op.drop_index(batch_op.f('ix_case_notes_case_id'))

    op.drop_table('case_notes')
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_events_event_type'))
        batch_op.drop_index('ix_case_events_case_time')

    op.drop_table('case_events')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accounts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_created_at'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_runs_status'))
        batch_op.drop_index(batch_op.f('ix_training_runs_model_name'))
        batch_op.drop_index(batch_op.f('ix_training_runs_experiment'))
        batch_op.drop_index(batch_op.f('ix_training_runs_created_at'))

    op.drop_table('training_runs')
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_system_metrics_name_time')
        batch_op.drop_index(batch_op.f('ix_system_metrics_component'))

    op.drop_table('system_metrics')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_rules_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_rules_is_active'))
        batch_op.drop_index(batch_op.f('ix_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_rules_code'))
        batch_op.drop_index(batch_op.f('ix_rules_category'))
        batch_op.drop_index('ix_rules_active_priority')

    op.drop_table('rules')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_quality_dataset_time')
        batch_op.drop_index(batch_op.f('ix_quality_checks_status'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_run_at'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_dimension'))
        batch_op.drop_index(batch_op.f('ix_quality_checks_dataset'))

    op.drop_table('quality_checks')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_created_at'))
        batch_op.drop_index(batch_op.f('ix_policies_category'))

    op.drop_table('policies')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_status'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_run_key'))
        batch_op.drop_index('ix_pipeline_runs_pipeline_time')
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_pipeline'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_target_role'))
        batch_op.drop_index(batch_op.f('ix_notifications_severity'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_category'))

    op.drop_table('notifications')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_stage'))
        batch_op.drop_index('ix_model_versions_name_version')
        batch_op.drop_index('ix_model_versions_name_stage')
        batch_op.drop_index(batch_op.f('ix_model_versions_name'))
        batch_op.drop_index(batch_op.f('ix_model_versions_created_at'))

    op.drop_table('model_versions')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_risk_score'))
        batch_op.drop_index(batch_op.f('ix_merchants_risk_band'))
        batch_op.drop_index(batch_op.f('ix_merchants_name'))
        batch_op.drop_index(batch_op.f('ix_merchants_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_merchants_high_risk_flag'))
        batch_op.drop_index(batch_op.f('ix_merchants_fraud_rate'))
        batch_op.drop_index(batch_op.f('ix_merchants_created_at'))
        batch_op.drop_index(batch_op.f('ix_merchants_country'))
        batch_op.drop_index('ix_merchants_category_risk')
        batch_op.drop_index(batch_op.f('ix_merchants_category'))

    op.drop_table('merchants')
    with op.batch_alter_table('lineage_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_lineage_source_target')
        batch_op.drop_index(batch_op.f('ix_lineage_edges_created_at'))

    op.drop_table('lineage_edges')
    with op.batch_alter_table('ingested_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingested_events_topic'))
        batch_op.drop_index(batch_op.f('ix_ingested_events_processed_at'))

    op.drop_table('ingested_events')
    with op.batch_alter_table('fraud_rings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_rings_status'))
        batch_op.drop_index(batch_op.f('ix_fraud_rings_risk_score'))
        batch_op.drop_index(batch_op.f('ix_fraud_rings_member_count'))
        batch_op.drop_index(batch_op.f('ix_fraud_rings_detection_method'))
        batch_op.drop_index(batch_op.f('ix_fraud_rings_created_at'))

    op.drop_table('fraud_rings')
    with op.batch_alter_table('drift_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drift_metrics_status'))
        batch_op.drop_index(batch_op.f('ix_drift_metrics_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_drift_metrics_drift_type'))
        batch_op.drop_index('ix_drift_feature_time')

    op.drop_table('drift_metrics')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_risk_score'))
        batch_op.drop_index(batch_op.f('ix_devices_is_blacklisted'))
        batch_op.drop_index(batch_op.f('ix_devices_distinct_customers'))
        batch_op.drop_index(batch_op.f('ix_devices_created_at'))

    op.drop_table('devices')
    with op.batch_alter_table('demo_scenario_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demo_scenario_runs_scenario_key'))
        batch_op.drop_index(batch_op.f('ix_demo_scenario_runs_created_at'))

    op.drop_table('demo_scenario_runs')
    with op.batch_alter_table('dead_letter_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letter_events_topic'))
        batch_op.drop_index(batch_op.f('ix_dead_letter_events_status'))
        batch_op.drop_index(batch_op.f('ix_dead_letter_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_dead_letter_events_created_at'))

    op.drop_table('dead_letter_events')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_quality_score'))
        batch_op.drop_index(batch_op.f('ix_datasets_name'))
        batch_op.drop_index(batch_op.f('ix_datasets_layer'))
        batch_op.drop_index(batch_op.f('ix_datasets_created_at'))
        batch_op.drop_index(batch_op.f('ix_datasets_classification'))

    op.drop_table('datasets')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_watchlisted'))
        batch_op.drop_index(batch_op.f('ix_customers_segment'))
        batch_op.drop_index(batch_op.f('ix_customers_risk_score'))
        batch_op.drop_index(batch_op.f('ix_customers_risk_band'))
        batch_op.drop_index('ix_customers_risk')
        batch_op.drop_index(batch_op.f('ix_customers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_created_at'))
        batch_op.drop_index('ix_customers_country_segment')
        batch_op.drop_index(batch_op.f('ix_customers_country'))

    op.drop_table('customers')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_status_priority')
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_risk_score'))
        batch_op.drop_index(batch_op.f('ix_cases_risk_band'))
        batch_op.drop_index(batch_op.f('ix_cases_resolution'))
        batch_op.drop_index(batch_op.f('ix_cases_priority'))
        batch_op.drop_index(batch_op.f('ix_cases_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_cases_fraud_ring_id'))
        batch_op.drop_index(batch_op.f('ix_cases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_cases_case_number'))
        batch_op.drop_index('ix_cases_assignee_status')
        batch_op.drop_index(batch_op.f('ix_cases_assigned_to'))

    op.drop_table('cases')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_actor_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_queries', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_queries_user_time')
        batch_op.drop_index(batch_op.f('ix_ai_queries_surface'))
        batch_op.drop_index(batch_op.f('ix_ai_queries_status'))
        batch_op.drop_index(batch_op.f('ix_ai_queries_intent'))
        batch_op.drop_index(batch_op.f('ix_ai_queries_created_at'))

    op.drop_table('ai_queries')
    # ### end Alembic commands ###
